# Generated by Django 5.2.3 on 2025-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplate',
            name='image',
            field=models.ImageField(max_length=255, upload_to='templates/'),
        ),
    ]
